### ISSUE TITLE
Manifest keys contain source path

### ISSUE THREAD

**Issue by bigskillet** [shellscape/webpack-manifest-plugin#238] opened 2020-12-19 02:55 UTC
- Manifest Plugin Version: 3.0.0
- Webpack Version: 5.11.0
- Reproduction: https://github.com/bigskillet/webpack-manifest-plugin

### Expected Behavior
```
  "/assets/main.css": "/assets/main-fed4ead9.css",
  "/assets/main.js": "/assets/main-31d6cfe0.js",
  "/assets/test.png": "/assets/test-7f730f47.png",
  "/assets/font.woff2": "/assets/font.woff2"
```

### Actual Behavior
```
  "/assets/main.css": "/assets/main-fed4ead9.css",
  "/assets/main.js": "/assets/main-31d6cfe0.js",
  "/assets/assets/test.png": "/assets/test-7f730f47.png",
  "/assets/index.html": "/index.html",
  "/assets/src/assets/static/font.woff2": "/assets/font.woff2"
```

### Additional Information
The manifest plugin is adding the source path the entry key. For example, `/src/assets/static/` is being added to the copied static font file. It's not adding the source path to the main.css and main.js keys though. I had to add a `basePath` to get them matching, which caused the test.png key to double the `/assets/` path and also added it to the index.html key. If I remove the `basePath`, the main entries don't match up:

- `"main.css": "/assets/main-fed4ead9.css"`
- `"main.js": "/assets/main-31d6cfe0.js"`

Sorry, I'm a bit of n00b, so I'm not sure if this is a bug, feature, or if I'm just using it wrong.

Thanks!

**Comment by n1c01ash** [comment] 2020-12-23 00:01
Its marked as a bug here: https://github.com/shellscape/webpack-manifest-plugin/issues/237#issue-766096887

**Comment by bigskillet** [comment] 2020-12-24 02:00
This map function seems to have resolved the issue and can be used as a temporary fix:
```
map: (file) => {
  file.name = file.name.replace(/(\.[a-f0-9]{32})(\..*)$/, '$2');
  return file;
}
```

**Comment by andrewmcodes** [comment] 2020-12-24 22:01
@bigskillet where exactly did you put that map?

**Comment by bigskillet** [comment] 2020-12-24 22:07
@andrewmcodes, here's my setup:
```
new WebpackManifestPlugin({
  fileName: 'assets/manifest.json',
  basePath: '/assets/',
  map: (file) => {
    file.name = file.name.replace(/(\.[a-f0-9]{32})(\..*)$/, '$2');
    return file;
  }
})
```

**Comment by coreyworrell** [comment] 2021-01-07 01:25
@bigskillet That fix seems to be for a separate issue where the hashes were in the keys. That `replace()` doesn't seem to remove the source path from the key, it would only remove the hash.

**Comment by bigskillet** [comment] 2021-01-07 16:28
@coreyworrell, I'm glad you chimed in, which gave me another look at this.

I thought the addition of the map fixed my issue, but I removed the map and it's working correctly right out of the box now. I'm going to chalk it up to user error on my end. I'm not sure what changed or what I was doing wrong before, but I blame the holidays when I originally posted this issue.

I'm going to close this since it's a non-issue.

**Comment by coreyworrell** [comment] 2021-01-07 17:21
@bigskillet oh that’s weird. I’m still experiencing the issue here, if I remove the map function then the source path still shows in the key.

**Comment by bigskillet** [comment] 2021-01-07 17:30
Weird!

I was testing with JS and CSS files only, but I just added a copied image and I see that the src path is still being included:
```
{
  "/assets/main.css": "/assets/main-170f3e42.css",
  "/assets/main.js": "/assets/main-dd84ccd5.js",
  "/assets/main.css.map": "/assets/main-170f3e42.css.map",
  "/assets/main.js.map": "/assets/main-dd84ccd5.js.map",
  "/assets/src/images/apple-touch-icon.png": "/assets/apple-touch-icon.png"
}
```
I added the map back in, but it's still adding the **/src/images/** path to the copied image key, as you can see above. So maybe that's not the solution either!

I'm going to reopen this, sigh...

**Comment by coreyworrell** [comment] 2021-01-08 21:03
Exactly what I'm experiencing as well. The main entries are fine, but other Asset Module files and assets are including the source path. Using the `map()` function in my previous comment fixes it for now, but may not continue to work well.

**Comment by bigskillet** [comment] 2021-01-09 15:05
Yeah and the map I was using before isn't working for me anymore. I tried using your version, which removes the src path, but it also adds the hash to the key, which I don't want.
```
{
  "/assets/main-170f3e42.css": "/assets/main-170f3e42.css",
  "/assets/main-dd84ccd5.js": "/assets/main-dd84ccd5.js",
  "/assets/main-170f3e42.css.map": "/assets/main-170f3e42.css.map",
  "/assets/main-dd84ccd5.js.map": "/assets/main-dd84ccd5.js.map",
  "/assets/apple-touch-icon.png": "/assets/apple-touch-icon.png"
}
```
I've tried using your map in combination with `removeKeyHash: true`, but that's not working either.
Any idea how to remove the hash as well?

**Comment by coreyworrell** [comment] 2021-01-09 16:51
Looks like your hashes are only 8 characters, so just change the `32` to an `8` in the map function and you should be good.

**Comment by bigskillet** [comment] 2021-01-09 18:15
@coreyworrell, yes that worked, thanks!
```
map: (file) => {
  file.name = file.name.replace(/(\.[a-f0-9]{8})(\..*)$/, '$2');
  return file;
}
```

**Comment by bigskillet** [comment] 2021-01-09 18:37
@coreyworrell, that's not working for me. I can set it to `0` and it removes the hash, but the src path is still in the key :(
```
map: (file) => {
  file.name = file.name.replace(/(\.[a-f0-9]{0})(\..*)$/, '$2');
  return file;
}
```
Changing your version to `8` or `0`, the src path is removed, but the hash still remains in the key:

`map: f => ({ ...f, name: f.path.replace(/\.[a-f0-9]{0}\./, '.') })`

**Comment by bigskillet** [comment] 2021-01-11 19:17
@coreyworrell, thanks, that worked!

**Comment by shellscape** [comment] 2021-01-17 15:05
Hey all, is this still an issue or is there a good workaround in place?

**Comment by bigskillet** [comment] 2021-01-17 16:56
Yes, still an issue. We're having to use the map filter as a workaround:

`map: f => ({ ...f, name: f.path.replace(/.[a-f0-9]{8}\./, '.') })`

**Comment by shellscape** [comment] 2021-01-17 17:03
OK thanks. If anyone would like to open a PR to fix this, it would be welcome.

**Comment by NovaLagnus** [comment] 2021-01-25 18:20
@bigskillet 
Try this:  https://webpack.js.org/plugins/copy-webpack-plugin/

**Comment by weaverryan** [comment] 2021-02-07 19:07
Hi! I may have fixed this on #249 - there are details on how to test at the bottom :).

**Comment by yoriiis** [comment] 2021-02-26 16:10
Any news about the fix and when the #249 will be merged?
I've test the PR from @weaverryan and the problem is resolved in my case, thanks you 👍

**Comment by shellscape** [comment] 2021-02-26 17:36
@yoriiis if you don't see any updates on the pull requests or issues, there is no news. I'll never understand why people ask this on GitHub when everything is available to see. please refrain from replies like this in this repo, as it just adds to noise.

**Comment by mrceperka** [comment] 2021-03-08 08:20
Hello, after upgrading to webpack 5, I have problem with combination of `WebpackManifestPlugin` and `CopyWebpackPlugin`.

_Problem:_
Tke keys in manifest file contains full source path:
```
node_modules/@some-vendor/ui/dist/images/icon-to-top.svg
```
instead of
```
ui-images/icon-to-top.svg
```
:point_up: This worked before, with webpack 4.

Any idea what I am doing wrong? 
Will #249 fix this issue as well?

_Config:_
```js
 new WebpackManifestPlugin({
      publicPath: 'assets/',
      // https://github.com/shellscape/webpack-manifest-plugin/issues/238
      map: (f) => {
        console.log(
          f.name,
          // this replace somehow fixes it...
          f.name.replace(
            'node_modules/@some-vendor/ui/dist/images',
            'ui-images'
          )
        )
        return f;
      },
    }),
    new CopyWebpackPlugin({
      patterns: [
        {
          from: path.resolve(
            __dirname,
            '../node_modules/@some-vendor/ui/dist/images'
          ),
          to: path.resolve(__dirname, '../../backend/www/assets') + '/ui-images',
        },
      ],
    }),
 ```

**Comment by bigskillet** [comment] 2021-03-08 13:45
This works for me, but I have to use the `map` mentioned above:
```
new CopyWebpackPlugin({
  patterns: [
    {
      from: 'src/static',
      to: 'assets'
    }
  ]
}),
new WebpackManifestPlugin({
  fileName: 'assets/manifest.json',
  map: f => ({ ...f, name: f.path.replace(/.[a-f0-9]{8}/, '') })
})
```

**Comment by mrceperka** [comment] 2021-03-08 14:01
I've tried yours and other versions of `map` from this thread, but none seemed to work.

I had to modify that `map` function a bit.
Because it did not work on strings like this: `node_modules/@some-vendor/ui/dist/images/icon-to-top.svg`

```js
'node_modules/@some-vendor/ui/dist/images/icon-to-top.svg'.replace(/.[a-f0-9]{8}/, '')
// bad
"node_modules/@some-vendor/ui/dist/images/icon-to-top.svg"
```

So instead I'm doing it in less generic way:
```js
'node_modules/@some-vendor/ui/dist/images/icon-to-top.svg'.replace('node_modules/@some-vendor/ui/dist/images', 'ui-images')
// good
'ui-images/icon-to-top.svg'
```

Anyway, I'd rather not use `map` at all :D

**Closed** 2021-04-01 13:55 UTC
Labels: c³ ⋅ PR welcome, c¹ ⋅ discussion

**Comment by bigskillet** [comment] 2021-04-01 21:10
I'm still having to use the map filter with the latest release 3.1.1 to remove the source path. Without it, the source path is still being added to non-css, non-js assets, like the image below:
```
new WebpackManifestPlugin({
  fileName: 'assets/manifest.json',
  basePath: '/assets/'
});
```
```
{
  "/assets/main.css": "/assets/main.b0b16a1f.css",
  "/assets/main.js": "/assets/main.9c57e099.js",
  "/assets/assets/apple-touch-icon.png": "/assets/apple-touch-icon.png",
  "/assets/main.b0b16a1f.css.map": "/assets/main.b0b16a1f.css.map",
  "/assets/main.9c57e099.js.map": "/assets/main.9c57e099.js.map"
}
```
