### ISSUE TITLE
Improve documentation about `webpack-manifest-plugin-after-emit` hook.

### ISSUE THREAD

**Issue by evilebottnawi** [shellscape/webpack-manifest-plugin#103] opened 2017-11-04 12:39 UTC
It will be great, thanks!

**Comment by a-x-** [comment] 2017-11-04 22:47
Hey,
I don't aware about `webpack-manifest-plugin-after-emit` hook so good.

This spec looks comprehensive: https://github.com/danethurber/webpack-manifest-plugin/blob/34257bc2da17c6f18ab64c4db938993d6143be47/spec/plugin.integration.spec.js#L68

We can add brief description and link to the spec.

**Comment by a-x-** [comment] 2017-11-04 22:50
Isn't [hooks options section](https://github.com/danethurber/webpack-manifest-plugin#hooks-options) fit your needs?

Can you describe your problem?

**Comment by a-x-** [comment] 2017-11-04 22:59
I see that this hook added recently
https://github.com/danethurber/webpack-manifest-plugin/pull/76

therefore, brief description might looks like this:

`webpack-manifest-plugin-after-emit` allows other plugins to use the manifest. Look at [patch](https://github.com/danethurber/webpack-manifest-plugin/pull/76) and [spec](https://github.com/danethurber/webpack-manifest-plugin/blob/34257bc2da17c6f18ab64c4db938993d6143be47/spec/plugin.integration.spec.js#L68) also.

**Comment by mastilver** [comment] 2017-11-06 14:35
yep, My bad, I shouldn't have merged that without the appropriate docs update

@a-x- Are you alright updating the doc?

**Comment by a-x-** [comment] 2017-11-08 06:57
Ok, sure. it's almost done.

**Comment by a-x-** [comment] 2017-11-08 08:17
https://github.com/danethurber/webpack-manifest-plugin/blob/doc/README.md#webpack-manifest-plugin-after-emit-hook

**Comment by evilebottnawi** [comment] 2018-04-11 10:55
@a-x- @mastilver friendly ping, not information in README after stable release

**Comment by Lalitha-Iyer** [comment] 2018-08-28 20:26
is this hook available in webpack 4 ?

**Comment by lili21** [comment] 2018-10-22 04:53
@Lalitha-Iyer You can use it in webpack 4.

```js
compiler.hooks.webpackManifestPluginAfterEmit.tap('MyPlugin', manifest => {
  //
})
```

**Comment by shellscape** [comment] 2020-10-25 16:13
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:13 UTC
