### ISSUE TITLE
Option to error if an asset is written that already exists in the seed object

### ISSUE THREAD

**Issue by philipwalton** [shellscape/webpack-manifest-plugin#82] opened 2017-09-09 00:52 UTC
I think this behavior should be the default, but if that's not possible at least adding an option to error/warn would be good.

I have several build tools all working with the same manifest, and I want to know if I've accidentally given two files the same name (with different hashes).

**Comment by mastilver** [comment] 2017-09-09 12:44
Did you try to use the reduce options?

You will have access to the current manifest and the one you are about to enter

**Comment by philipwalton** [comment] 2017-09-13 05:00
Thanks, reduce will probably work for my use case, though I do think there's value in having it be a standalone option.

**Comment by mastilver** [comment] 2017-09-13 08:46
Im leaving it open, as I'm not strongly against it. Give me some time to think about it and any issue that might appears if that on. Having on by default would be the best I think

Just so you are aware, we **might** deprecate `reduce` in the next major version, see: https://github.com/danethurber/webpack-manifest-plugin/pull/79#issuecomment-328794520

**Comment by shellscape** [comment] 2020-10-25 16:12
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:12 UTC
