### ISSUE TITLE
Breaks when chunk has multiple files with the same extension

### ISSUE THREAD

**Issue by kostasmanionis** [shellscape/webpack-manifest-plugin#30] opened 2016-10-14 09:23 UTC
Hello!

Since this package builds the memo object keys only using the chunk name and the file extension([see here](https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L49)), it breaks when the chunk has multiple files with the same extension. For e.g.

```
index.css
index.above.css
```

It outputs something like this

`"/fancy/project/dist/index.css": "/fancy/project/dist/index.99b9974b.above.css"`

I could send in a PR if we could agree on how to handle these cases.

**Comment by mastilver** [comment] 2017-07-09 16:58
hi @kostasmanionis 

Can you be clearer on this? What's your webpack config?

**Comment by mastilver** [comment] 2017-07-09 17:10
^ ping @nitruxa @yuya373 @sashalifestar @993318936 @bobaaaaa @harryurban

**Comment by bobaaaaa** [comment] 2017-07-11 09:42
Hi. This is our project setup.

## Setup

- TypeScript 2.4.1
- Webpack 3.1
- webpack-manifest-plugin 1.1.2
- extract-text-webpack-plugin 2.1.2

```typescript
// main.ts
import '../scss/foo.critical.scss';
import '../scss/foo.main.scss';
```

```js
// webpack.conf.js (simple)
{
  module: {
    rules: [
      {
        test: /\.main\.scss$/,
        use: ExtractTextPluginMainCss
      },
      {
        test: /\.critical\.scss$/,
        use: ExtractTextPluginCriticalCss
      }
    ]
  },
  plugins: [
    new ManifestPlugin()
  ]
}
```

## Expected manifest.json output
```json
{
  "foo.main.css": "foo.main.$hash.css",
  "foo.critical.css": "foo.critical.$hash.css"
}
```

## Actual manifest.json output
```json
{
  "foo.main.css": "foo.main.$hash.css"
}
```

**Comment by mastilver** [comment] 2017-07-11 09:46
I see, I didn't think about the case when you have multiples `ExtractTextPlugin`

**Comment by kostasmanionis** [comment] 2017-07-11 09:59
The config that @bobaaaaa shared illustrates the issue perfectly 👍  I've ended up with using `webpack-assets-manifest` with the `fileExtRegex` option. Maybe a similar solution would work here.

**Comment by bobaaaaa** [comment] 2017-07-11 13:42
@kostasmanionis thx for the tip. I have a workaround with a different CSS loader chain + webpack-manifest-plugin

**Comment by mastilver** [comment] 2017-07-24 17:07
I think fixing #23 will also fix that issue

**Comment by mastilver** [comment] 2017-08-09 21:14
At the moment it's possible to use the map option to resolve it:
https://github.com/danethurber/webpack-manifest-plugin/blob/master/spec/plugin.spec.js#L545-L566

I'm keeping it open, but I'm not sure it's that easy to fix...

**Comment by kostasmanionis** [comment] 2017-08-10 12:06
@mastilver agree that it's not an easy fix out of the box. Should be good enough that an _escape hatch_ is provided for people who want more control over their manifest.

thanks! :+1:

**Comment by jheander** [comment] 2017-11-09 09:56
@mastilver The suggested map function doesn't seem to affect the problem, it just adds the full directory to the output manifest but the extra css files are still not added to the manifest. Just a single line with the first css file.

**Comment by mastilver** [comment] 2017-11-09 10:12
@jheander I can't help you without more information, send us your webpack config

**Comment by jheander** [comment] 2017-11-10 07:40
Sure! So this is out setup:

- Webpack 3.6.0
- webpack-manifest-plugin 1.3.2
- extract-text-webpack-plugin 3.0.2

```
// entry.js
import 'style/tzcontrol.less';
import 'style/tzcontrol.scss';
import 'style/tz-appshell.less';
```

```
// webpack.conf
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');

const extractSass = new ExtractTextPlugin(`[name]-[contenthash]-new.css`);
const extractLess = new ExtractTextPlugin(`[name]-[contenthash].css`);
const extractShell = new ExtractTextPlugin(`[name]-[contenthash]-shell.css`);

config.module.rules = [
    {
        test: /\.scss$/,
        include: [
            path.resolve(__dirname, 'src/style'),
        ],
        loader: extractSass.extract({
            use: ['css-loader', 'sass-loader'],
            fallback: 'style-loader',
            publicPath: './',
        }),
    },
    {
        test: /\.less$/,
        include: [
            path.resolve(__dirname, 'src/style'),
        ],
        exclude: [
            path.resolve(__dirname, 'src/style/tz-appshell.less'),
        ],
        loader: extractLess.extract({
            use: ['css-loader', 'less-loader'],
            fallback: 'style-loader',
            publicPath: './',
        }),
    },
    {
        test: /\.less$/,
        include: [
            path.resolve(__dirname, 'src/style/tz-appshell.less'),
        ],
        loader: extractShell.extract({
            use: ['css-loader', 'less-loader'],
            fallback: 'style-loader',
            publicPath: './',
        }),
    },
];

config.plugins = [
    extractLess,
    extractSass,
    extractShell,
    new ManifestPlugin({
      map: function(file) { 
         file.name = path.join(path.dirname(file.path), file.name); 
         return file; 
       } 
    }),
];
```

## Expected manifest.json output
```
{
  ...
  "app.css": "app-c5d773788e95ba4c03ea1c1e306fef61.css",
  "app-new.css": "app-c06bf711eecbd8785ddf0737986d8343daad8681-new.css",
  "app-shell.css": "app-54e823c0625da14e976b6d1cef1a36a971527a1a-shell.css",
  ...
}
```

## Actual manifest.json output
```
{
  ...
  "/assets/app.css": "/assets/app-c5d773788e95ba4c03ea1c1e306fef61.css",
  ...
}
```

**Comment by lnrb0b** [comment] 2017-11-14 17:45
I encountered this problem today and worked around it by simply removing the hash in the file name using map. My case was slightly different to this but I've modified my solution to this use case and hopefully the below will help.

Hopefully for you this will work:
```
new ManifestPlugin({
    map: function(file) { 
        file.name = file.path.replace(`-${file.chunk.hash}`, '');
        return file; 
    },
}),
```
However the hash we are using may be the same for all files with the same entry (a problem I had). If so you could do a messier version:
```
new ManifestPlugin({
    map: function(file) { 
        file.name = file.path.replace(/-[a-z0-9].+\.(css|js)/i, '.$1');
        return file; 
    },
}),
```
Neither of these are tested, but maybe they will help you get a workaround in place 😄

**Comment by squidfunk** [comment] 2017-11-21 12:28
+1

**Comment by shellscape** [comment] 2020-10-25 16:12
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:12 UTC
