### ISSUE TITLE
Non deterministic value

### ISSUE THREAD

**Issue by yannski** [shellscape/webpack-manifest-plugin#119] opened 2018-02-15 15:39 UTC
Assuming I require some images twice in my JS with something like (first require is to have an original image, second require is for thumbnail generation):
```js
importAll(require.context('images/blog/', true, /\.(png|jpe?g|svg)$/))
importAll(require.context('!file-loader?name=[path][name]-thumbnail-[hash].[ext]&context=app/javascript!image-webpack-loader!image-process-loader?resize[]=600&resize[]=360!images/blog/', true, /banner\.jpg$/))
```
The value generated in the manifest is not deterministic. For some images the value will be the result of the first require and for some other images it will be the second require.

How can I require some images several times and still have the several generated occurrences as key/value in the manifest.json file?

**Comment by mastilver** [comment] 2018-04-08 16:06
I'm not sure I understand your issue

Can you give us the manifest you get and the expected one

**Comment by shellscape** [comment] 2020-10-25 16:17
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:17 UTC
