### ISSUE TITLE
custom asset added to webpack compilation not showing up in manifest

### ISSUE THREAD

**Issue by vinothvk** [shellscape/webpack-manifest-plugin#124] opened 2018-02-22 01:08 UTC
I have a logic to add a custom json asset to webpack compilation output, but the file info is not getting appended to the manifest. Is there any sample for me to validate what i am doing is correct ?

In the webpack compiler emit event hook i have the logic below 

compilation.assets[fileName] = {
            source: () => fileContent,
            size: () => fileContent.length
          }

Thanks

**Comment by mastilver** [comment] 2018-02-22 10:27
Are you using `v2`

**Comment by vinothvk** [comment] 2018-02-22 14:28
Nope v1. I see v2 rc1 has some changes related to assets. Do you want me to try that version ?. Thanks for the reply

**Comment by shellscape** [comment] 2020-10-25 16:17
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:17 UTC
