### ISSUE TITLE
Feature request: option to generate key based on the physical location

### ISSUE THREAD

**Issue by davidkron** [shellscape/webpack-manifest-plugin#178] opened 2018-11-24 20:47 UTC
I'm currently in the process of modernizing an existing server-side rendered application by migrating the client-side code to a asset pipeline based on webpack. To generate the appropriate paths server-side I require the help of a manifest to translate simple file paths to the effective output after webpack has built everything (including hash).

In my production build I am using a flat folder output configuration simply based on the hash of assets:
```
{
	test: /\.(png|svg|jpg|gif)$/,
	use: [
		{
			loader: 'file-loader',
			options: {
				name: '[hash].[ext]'
			}
		}
	]
}
```

The manifest plugin will generate something like this, where the key is always just the filename without any folder structure:
```
{
     "logo.png": "85626904b63ff423ce8c4357f9c92b3f.png"
}
```

This is problematic for my server-side code as I cannot resolve my files using their physical locations, e.g. `static/images/logo.png`. Another problem of the current approach is if i have a file with the same name in different locations, e.g. `static/images/hi-res/logo.png` or `static/images/low-res/logo.png`. In this case the manifest will only have one entry (because the key will just be "logo.png"). Also which one of the two possibilities will be the resulting value in the manifest might not even be deterministic.

Because of such scenarios, I think it would be very useful to have an option to generate manifest keys based on the physical location of the source files (inclusive folders) instead of just the basename of a file.

**Comment by shellscape** [comment] 2020-10-25 16:26
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Closed by shellscape** 2020-10-25 16:26 UTC
