### ISSUE TITLE
manifest.json generated with wrong filename

### ISSUE THREAD

**Issue by Mukhametvaleev** [shellscape/webpack-manifest-plugin#250] opened 2021-02-10 16:28 UTC
- Manifest Plugin Version: 3.0.0
- Webpack Version: 5.21.2
- Operating System (or Browser): macOS Big Sur
- Node Version: v15.7.0
- Link to reproduction: https://codesandbox.io/s/loving-archimedes-sgp20?file=/static/frontend/manifest.json

 **Webpack config:**
```
const path = require('path');

const { WebpackManifestPlugin } = require('webpack-manifest-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    context: path.resolve(__dirname, 'src'),
    entry: ['./index.tsx'],
    mode: 'development',
    module: {
        rules: [
            {
                exclude: /node_modules/,
                test: /\.(ts|tsx)?$/,
                use: ['babel-loader', 'ts-loader'],
            },
        ],
    },
    plugins: [new CleanWebpackPlugin(), new WebpackManifestPlugin()],
    resolve: {
        extensions: ['.ts', '.tsx', '.js'],
    },
    output: {
        path: path.resolve(__dirname, 'static/frontend/'),
        filename: '[name].[hash].js',
    },
};
```

### Expected Behavior
`{
  "main.js": "main.6b7fd6ac2fd4fec33833.js"
}`

### Actual Behavior
`{
  "main.js": "automain.6b7fd6ac2fd4fec33833.js"
}`

Weird "auto" prefix in filename as `publicPath`.

**Comment by shellscape** [comment] 2021-02-10 16:51
Duplicate of #229. Please search issues before creating new ones.

**Closed by shellscape** 2021-02-10 16:51 UTC
