### ISSUE TITLE
Support webpack@5

### ISSUE THREAD

**Issue by irudoy** [shellscape/webpack-manifest-plugin#186] opened 2019-03-29 15:00 UTC
```
TypeError: Cannot read property 'call' of undefined
    at ManifestPlugin.<anonymous> (/.../node_modules/webpack-manifest-plugin/lib/plugin.js:191:53)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/.../node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/.../node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/.../node_modules/webpack/lib/Compiler.js:448:19)
    at process.nextTick (/.../node_modules/webpack/lib/Compiler.js:249:10)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
(node:28406) DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
```

**Comment by xeonicca** [comment] 2019-04-02 07:51
I am getting the same error in webpack v4 when compilation is triggered by watch mode. Any solutions?

**Comment by mAAdhaTTah** [comment] 2019-04-03 20:52
I'm getting this error on webpack@4 w/ multiple compilers (e.g. `module.exports = [... multiple configs ...]`).

**Comment by xeonicca** [comment] 2019-04-03 22:48
I had the same problem and mine was caused by  smart measure webpack plugin which may fail during incremental build.

**Comment by ycjcl868** [comment] 2019-06-19 03:44
same problems

**Comment by VictorQueiroz** [comment] 2019-07-11 22:15
I also have the same problem using the multi-compiler feature. How can we fix this?

**Comment by mastilver** [comment] 2019-10-02 16:59
Can you all confirm it's been fixed on 2.2.0? (thank you @ian-craig )

**Comment by ian-craig** [comment] 2019-10-03 02:02
2.2.0 with Webpack 5.0.0-alpha.26 seems to be working correctly in my project. I just have a simple setup though, so no other plugins depending on the manifest or anything.

**Comment by kirill-konshin** [comment] 2019-11-06 22:04
There are other problems too:

```
✖ ｢wdm｣: TypeError: Cannot read property 'length' of undefined
    at /Users/dis/Sites/web-modules-core/build/node_modules/webpack-manifest-plugin/lib/plugin.js:129:39
    at Array.reduce (<anonymous>)
    at ManifestPlugin.<anonymous> (/xxx/node_modules/webpack-manifest-plugin/lib/plugin.js:116:26)
    at _next0 (eval at create (/xxx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at eval (eval at create (/xxx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at /xxx/node_modules/html-webpack-plugin/index.js:317:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ceesvanegmond** [comment] 2020-03-26 16:05
Got same problem as @kirill-konshin .

**Comment by kirill-konshin** [comment] 2020-04-17 21:57
Seems to be working now, noticed one issue though: `webpack-manifest-plugin@3.0.0-rc.0" has unmet peer dependency "webpack@4".`

**Comment by keeganstreet** [comment] 2020-07-28 03:55
Hi, this error is still occurring with `webpack-manifest-plugin@2.2.0` and `webpack@5.0.0-beta.22`. Here is the error message:

```
[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
at node_modules/webpack-manifest-plugin/lib/plugin.js:129:39
at Array.reduce (<anonymous>)
at ManifestPlugin.<anonymous> (node_modules/webpack-manifest-plugin/lib/plugin.js:116:26)
```

Here's the line that is treating `compilation.chunks` as an `Array`, when it is now a `Set`: https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L87

**Comment by keeganstreet** [comment] 2020-07-28 04:52
I wrapped `compilation.chunks`, `chunk.files`, and `stats.assets` in `Array.from` just to get a build working. Webpack is giving another warning about this module:

```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

**Comment by arxeiss** [comment] 2020-08-23 21:31
So I tried to make it work as @keeganstreet suggested with `Array.from` wraps.  And this is what I did to work with Webpack 5. It is not ideal, but acceptable for me for now.

**webpack.config.js**
```diff
- const ManifestPlugin = require('webpack-manifest-plugin');
+ const ManifestPlugin = require('./webpack-manifest-plugin'); // local file
```

Then I downloaded the current JS file from the master branch. [lib/plugin.js](https://github.com/danethurber/webpack-manifest-plugin/blob/63d3ee243809121f2db258e910a58f0288faee7e/lib/plugin.js) and saved it next to `webpack.config.js` with name `webpack-manifest-plugin.js`. And updated those lines:

**webpack-manifest-plugin.js**
```diff
// This changes is on line 87
- var files = compilation.chunks.reduce(function(files, chunk) {
+ var files = Array.from(compilation.chunks).reduce(function(files, chunk) {

// This changes is on line 128
// From Webpack 5, I think "the hack" where this code lives is not needed.
// So I'm returning files directly. Otherwise ignore the return and use the rest
- var isEntryAsset = asset.chunks.length > 0;
+ return files;
+ var isEntryAsset = Array.from(asset.chunks || []).length > 0;
```

Hope this helps someone to use this plugin with Webpack 5 until the proper fix will be released. There are some pitfalls with this approach still.

**Comment by kirill-konshin** [comment] 2020-08-24 18:23
FYI, I've successfully used `"webpack-manifest-plugin": "3.0.0-rc.0"`.

**Comment by shellscape** [comment] 2020-10-18 02:47
Hey folks, please see #222 for updates on v5 support.

**Closed by shellscape** 2020-10-18 02:47 UTC
